### ISSUE TITLE
Possible issue with icons

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#217] opened 2021-09-06 16:26 UTC
We have this report: https://wordpress.org/support/topic/series-icon-image/

I can see similar issues with the icon. I get these db errors:

WordPress database error Table 'jttnrbqayz.wp_orgseriesicons' doesn't exist for query SELECT icon FROM wp_orgseriesicons WHERE term_id=187 made by WP_List_Table->display, WP_Terms_List_Table->display_rows_or_placeholder, WP_Terms_List_Table->single_row, WP_List_Table->single_row_columns, WP_Terms_List_Table->column_default, apply_filters('manage_series_custom_column'), WP_Hook->apply_filters, manage_series_columns_action, series_get_icons

<img width="625" alt="Screen Shot 2021-09-06 at 12 26 19 PM" src="https://user-images.githubusercontent.com/3868028/132244677-5ebaf537-17da-4ccd-8955-36bb96a23541.png">

**Comment by olatechpro** [comment] 2021-09-07 10:08
The problem is activation hook not firing on plugin activation as it point to only file name. So, it's fixed now but the user may need to deactivate and re activate the plugin again just incase they go through file upload to upgrade.

**Closed** 2021-09-07 10:10 UTC
