### ISSUE TITLE
Can not be enabled on PHP 5.6

### ISSUE THREAD

**Issue by stevejburge** [publishpress/publishpress-series#540] opened 2022-06-16 14:52 UTC
![Screen Shot 2022-06-16 at 10 52 18 AM](https://user-images.githubusercontent.com/3868028/174097953-28d0a464-3a37-448d-8c83-650e17f01ed0.png)

**Comment by olatechpro** [comment] 2022-06-16 15:44
This is duplicate of https://github.com/publishpress/publishpress-series/issues/535 that was merged this week

**Closed** 2022-06-23 15:59 UTC
Labels: confirmed bug
